name: group-manager-bot

services:
  bot-app:
    image: python:3.11
    container_name: group-manager-bot-app
    restart: always
    command: bash appRun.sh
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
