name: group-manager-bot

services:
  bot-app:
    image: python:3.11
    container_name: group-manager-bot-app
    restart: always
    command: bash -c "pip3 install -r requirements.txt && python3 main.py"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
